# Sprint 1


### Mekala Bhargav
### N.Pavan
### Munjuru Bharadwaja
### Nariboyina pavan sai


## Team Id:PNT2022TMID03630

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
import warnings
warnings.filterwarnings(action="ignore")
%matplotlib inline
pd.set_option("display.max_rows",1000)
pd.set_option("display.max_columns",1000)

### Reading Dataset and showing first 15 instances of Dataset

In [8]:
fires=pd.read_csv("C:\SANMIKA\IBM Project\Forest_Fires.csv")
fires.head(20)

    X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
0   7  5      7    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1   7  4     10    5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2   7  4     10    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3   8  6      7    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4   8  6      7    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5   8  6      1    3  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
6   8  6      1    1  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
7   8  6      1    1  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
8   8  6     11    5  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
9   7  5     11    2  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0
10  7  5     11    2  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.0
11  7  5     11    2  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.0
12  6  5      1    0  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.0
13  6  5     11    1  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.0
14  6  5     11    6  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.0
15  6  5     11    0  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.0
16  5  5      7    2  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.0
17  8  5     10    1  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.0
18  6  4      7    6  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.0
19  6  4      0    2  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.0

### Last 20 instances of Dataset

In [4]:
fires.tail(20)

     X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
493  3  4      1    5  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
494  6  5      1    5  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
495  7  5      1    5  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
496  8  6      1    5  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
497  7  5      1    5  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
498  4  4      1    5  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
499  2  4      1    6  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
500  4  3      1    6  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
501  1  2      1    4  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
502  1  2      1    0  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
503  2  4      1    0  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
504  1  2      1    0  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
505  5  4      1    0  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
506  6  5      1    0  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
507  8  6      1    3  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
508  4  3      1    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
509  2  4      1    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
510  7  4      1    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
511  1  4      1    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
512  6  3      9    5  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

### Descriptive Statistics of each attribute

In [5]:
fires.describe().T

       count        mean         std   min    25%     50%     75%      max
X      513.0    4.678363    2.320059   1.0    3.0    4.00    7.00     9.00
Y      513.0    4.300195    1.230925   2.0    4.0    4.00    5.00     9.00
month  513.0    5.773879    4.379857   0.0    1.0    6.00   11.00    11.00
day    513.0    2.736842    1.923068   0.0    1.0    3.00    4.00     6.00
FFMC   513.0   90.637427    5.540920  18.7   90.2   91.60   92.90    96.20
DMC    513.0  110.989279   64.191013   1.1   68.6  108.30  142.40   291.30
DC     513.0  549.155166  247.724594   7.9  440.9  664.50  713.90   860.60
ISI    513.0    9.023587    4.575543   0.0    6.4    8.40   11.00    56.10
temp   513.0   18.887524    5.828128   2.2   15.5   19.30   22.80    33.30
RH     513.0   44.348928   16.358803  15.0   33.0   42.00   53.00   100.00
wind   513.0    4.010526    1.796613   0.4    2.7    4.00    4.90     9.40
rain   513.0    0.021832    0.297107   0.0    0.0    0.00    0.00     6.40
area   513.0   12.891598   63.892586   0.0    0.0    0.54    6.57  1090.84

### Prediction of fire if the area is already burnt where "0" represent no fire  detected and "1" represent fire detected changing all values when values are not "0" and "1"
### Renaming for easy view

In [6]:
fires['area'].values[fires['area'].values>0]=1
fires=fires.rename(columns={'area':'output'})
fires.head(10)

   X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  output
0  7  5      7    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0     0.0
1  7  4     10    5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0     0.0
2  7  4     10    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0     0.0
3  8  6      7    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2     0.0
4  8  6      7    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0     0.0
5  8  6      1    3  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0     0.0
6  8  6      1    1  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0     0.0
7  8  6      1    1  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0     0.0
8  8  6     11    5  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0     0.0
9  7  5     11    2  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0     0.0

### Compute pairwise correlation of all columns

In [7]:
fires.corr()

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,output
X,1.000000,0.542705,-0.019280,-0.010253,-0.020499,-0.048861,-0.088801,0.006033,-0.051070,0.083757,0.020869,0.065176,0.059818
Y,0.542705,1.000000,-0.065274,0.037564,-0.045979,0.008210,-0.098496,-0.023142,-0.023871,0.062587,-0.019537,0.033313,0.057920
month,-0.019280,-0.065274,1.000000,-0.147834,-0.006918,-0.172128,0.223656,-0.171371,-0.072937,-0.102810,-0.139239,-0.077249,-0.015320
day,-0.010253,0.037564,-0.147834,1.000000,0.074758,0.068931,0.052906,0.116486,0.148440,-0.105351,-0.035433,0.053147,0.044270
FFMC,-0.020499,-0.045979,-0.006918,0.074758,1.000000,0.383641,0.332936,0.532083,0.431609,-0.300827,-0.029208,0.056806,0.074767
DMC,-0.048861,0.008210,-0.172128,0.068931,0.383641,1.000000,0.681741,0.304585,0.469590,0.071711,-0.105111,0.074780,0.065686
DC,-0.088801,-0.098496,0.223656,0.052906,0.332936,0.681741,1.000000,0.228168,0.497584,-0.044067,-0.203010,0.035690,0.099845
ISI,0.006033,-0.023142,-0.171371,0.116486,0.532083,0.304585,0.228168,1.000000,0.394217,-0.133363,0.106825,0.067664,0.036423
temp,-0.051070,-0.023871,-0.072937,0.148440,0.431609,0.469590,0.497584,0.394217,1.000000,-0.528670,-0.227618,0.069526,0.077936
RH,0.083757,0.062587,-0.102810,-0.105351,-0.300827,0.071711,-0.044067,-0.133363,-0.528670,1.000000,0.071433,0.099616,-0.035554
wind,0.020869,-0.019537,-0.139239,-0.035433,-0.029208,-0.105111,-0.203010,0.106825,-0.227618,0.071433,1.000000,0.061479,0.058213
rain,0.065176,0.033313,-0.077249,0.053147,0.056806,0.074780,0.035690,0.067664,0.069526,0.099616,0.061479,1.000000,0.025342
output,0.059818,0.057920,-0.015320,0.044270,0.074767,0.065686,0.099845,0.036423,0.077936,-0.035554,0.058213,0.025342,1.000000